add Unchecked Math questions
fullstack-development/blockchain-developers-roadmap pull request #24
Opened 2023-03-22 13:25 UTC by bimkon144

2023-03-23 04:46 UTC, PavelNaydanov reviewed
Надо поменять целевую ветку с main на dev. Чтобы PR был в dev ветку.

2023-03-23 04:46 UTC, PavelNaydanov commented on solidity/junior-2/solidity/theory/questions.md
> +  - Что произойдет если к uint8 = 255 прибавить 1? Какое значение будет uint8?
Я хочу предложить сделать прям мини примерчики на эти пункты и как-то обыграть. Например, что вернет функция ```getCounter()```, когда используем unchecked?. Потом пример, когда не используем. Как-нибудь так.
```solidity
contract Counter {
   uint8 _counter= 255;
   
   function increase() external {
       // TODO: добавить unchecked
       _counter++;
   }

  function getCounter() external returns(uint8) {
     return _counter;
  }
}

 
```
Во второй ссылке это есть. Можно аналогичные простенькие свои примерчики накидать

2023-04-19 03:47 UTC, rlkvrv requested changes

2023-04-19 03:47 UTC, rlkvrv commented on solidity/junior-2/solidity/theory/questions.md
> +2. Для чего использовалась библиотека Safe Math от openzeppelin?Нужно ли в версии solidity версии выше 0.8 использовать такую библиотеку?
Тут пробела не хватает между "openzeppelin?Нужно")

2023-04-19 03:48 UTC, rlkvrv approved these changes

2023-05-19 03:47 UTC, PavelNaydanov commented on solidity/junior-2/solidity/theory/questions.md
> +2. Для чего использовалась библиотека Safe Math от openzeppelin?Нужно ли в версии solidity версии выше 0.8 использовать такую библиотеку?
Добавил

2023-05-19 03:48 UTC, merged